[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@aave/core-v3=lib/aave-v3-core/contracts", "@uniswap/v3-periphery=lib/uniswap-v3-periphery/contracts", "@uniswap/v3-core=lib/uniswap-v3-core/contracts"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
